<div id="bd" role="main">
<div id="yui-main">
                <div class="yui-b">                        
			<div class="yui-ge">                                
				<div class="yui-u first">
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas sit amet metus. Nunc quam elit, posuere nec, auctor in, rhoncus quis, dui. Aliquam erat volutpat. Ut dignissim, massa sit amet dignissim cursus, quam lacus feugiat.    
                                </div>
                                <div class="yui-u">
Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas sit amet metus. Nunc quam elit, posuere nec, auctor in, rhoncus quis, dui. Aliquam erat volutpat. Ut dignissim, 
massa sit amet dignissim cursus, quam lacus feugiat.                                    
				</div>
                        </div>
                </div>
        </div>
        <div class="yui-b">Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Maecenas sit amet metus. Nunc quam elit, posuere nec, auctor in, rhoncus quis, dui. Aliquam erat volutpat. Ut dignissim, 
massa sit amet dignissim cursus, quam lacus feugiat.
        </div>
</div>
